version: "3"

services:

  db:

    image: "mariadb:10.5"

    command: --default-authentication-plugin=mysql_native_password
    restart: always
    
    ports:
      - "32000:3306"

    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

    volumes:
      - './db:/var/lib/mysql'
  
  web:

    build: ./app

    env_file: "./.env"

    command: bash -c "./wait-for-it.sh -t 60 db:3306 && flask init-db && flask run"

    links:
      - db

    ports:

      - "5000:5000"
    env_file: .env


    volumes:
      - ./app:/app
