version: "3"

services:

  db:

    image: "mariadb:10.5"

    command: --default-authentication-plugin=mysql_native_password
    restart: always
    
    ports:
      - "32000:3306"
    env_file:
      - ".env"

    volumes:
      - './db:/var/lib/mysql'
  
  web:

    build: .

    env_file: ".env"

    command: bash -c "./wait-for-it.sh -t 60 db:3306 && flask init-db && flask run"
    restart: always

    links:
      - db

    ports:

      - "6000:5000"
    env_file: ".env"


    volumes:
      - ./app:/app
